### PR TITLE
Add missing -R options on setfacl

### PR DESCRIPTION
**Pull request by Soullivaneuh**
According to [this problem](http://serverfault.com/q/670788/270824), `-R` option must be present to ensure full files permissions.

Can you please submit a new stable version after merge this PR?

Thanks.

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
Up. Could this PR be merged? It's quite critical as file cannot be deleted without this option.

Thanks.

**Comment by Soullivaneuh** [comment]
ping @peterjmit

**Comment by Soullivaneuh** [comment]
@peterjmit This PR is quite **critical** for deploys. Can you please review it?

Is this project still maintained? Need help?

Regards

**Comment by peterjmit** [comment]
@Soullivaneuh not abandoned - I am just very busy with a new job! Sorry about the delay here. I will cut a new release this evening.

Thank you for your contribution!

**Comment by Soullivaneuh** [comment]
Thanks you. :+1: 

Waiting for the new release.

Don't hesitate to ping me if you need help to maintain this project. ;-)

**Comment by peterjmit** [comment]
Published on rubygems now!

https://github.com/capistrano/file-permissions/releases/tag/0.1.1

**Comment by Soullivaneuh** [comment]
Great, thanks! :+1:

**Pull request merged**
